Feature/introduction
xavierang/shopify pull request #7
Opened 2018-02-05 05:26 UTC by xavierang

2018-02-05 22:05 UTC, dillonbailey requested changes

2018-02-05 22:05 UTC, dillonbailey commented on src/html/shared/introduction.html
> +                        <img src="../images/logo-lightbg.png" alt="Shopiflight logo" class="c-logo">
@xavierang replace with some SVG action - can ask the designers if needed :)

2018-02-05 23:37 UTC, xavianaxw requested changes
Might want to rename _components.overlay to _components.menu

2018-02-06 22:27 UTC, xavianaxw approved these changes

2018-02-06 22:53 UTC, merged